FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_LANDING_URL

ENV VITE_LANDING_URL=$VITE_LANDING_URL

COPY rooiam-docs/package*.json ./
RUN npm install
COPY rooiam-docs/ ./
COPY docs/ /docs/
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

