FROM node:20-alpine AS build

WORKDIR /app

ARG VITE_API_URL
ARG VITE_DOCS_URL

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_DOCS_URL=$VITE_DOCS_URL

COPY rooiam-admin/package*.json ./
RUN npm install
COPY rooiam-admin/ ./
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

