FROM node:20-alpine AS build

WORKDIR /app

COPY rooiam-book/package*.json ./
RUN npm install
COPY rooiam-book/ ./
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
COPY --from=build /app/next.config.mjs ./
COPY --from=build /app/public ./public
COPY --from=build /app/.next ./.next
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json

EXPOSE 5176

CMD ["npm", "run", "start"]
