export const GITHUB_REPO_URL = 'https://github.com/theparitt/rooiam'
export const DOCS_BASE_URL = import.meta.env.VITE_DOCS_URL?.trim() || 'http://localhost:5175'
export const APP_BASE_URL = import.meta.env.VITE_APP_URL?.trim() || 'http://localhost:5172'
export const DEMO_BASE_URL = import.meta.env.VITE_DEMO_URL?.trim() || 'http://localhost:5183'
export const DEMO_APP_BASE_URL = import.meta.env.VITE_DEMO_APP_URL?.trim() || 'http://localhost:5182'
export const DEMO_ADMIN_BASE_URL = import.meta.env.VITE_DEMO_ADMIN_URL?.trim() || 'http://localhost:5181'
export const DOCS_HOME_URL = `${DOCS_BASE_URL}/`
export const DOCS_GETTING_STARTED_URL = `${DOCS_BASE_URL}/getting-started`
export const DOCS_OVERVIEW_URL = `${DOCS_BASE_URL}/overview`
export const DOCS_DEMO_URL = `${DOCS_BASE_URL}/demo`
export const DOCS_DEVELOPMENT_URL = `${DOCS_BASE_URL}/development`
export const DOCS_PRODUCTION_URL = `${DOCS_BASE_URL}/production`
export const DOCS_DEVELOPERS_URL = `${DOCS_BASE_URL}/developers`
export const DOCS_SECURITY_URL = `${DOCS_BASE_URL}/security`
export const DOCS_TROUBLESHOOTING_URL = `${DOCS_BASE_URL}/troubleshooting`
export const DEMO_APP_URL = `${DEMO_BASE_URL}/`
export const DEMO_PORTAL_URL = `${DEMO_APP_BASE_URL}/`
export const DEMO_ADMIN_URL = `${DEMO_ADMIN_BASE_URL}/`
