ALTER TABLE organizations
    ADD COLUMN allow_magic_link BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN allow_google BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN allow_microsoft BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN allow_passkey BOOLEAN NOT NULL DEFAULT TRUE;
