ALTER TABLE organizations
    ADD COLUMN IF NOT EXISTS show_login_logo BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS show_login_title BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS show_login_subtitle BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS show_powered_by BOOLEAN NOT NULL DEFAULT FALSE;
